name: FunnyGames
main: AleoTV\main
version: 1.0
api: [3.0.0,4.0.0]
author: AleoTV
load: STARTUP
commands:
  tag:
    description: §rTo Set the time to day.
    usage: "/day"
    permission: time.command
  nacht:
    description: §rTo Set the time to night
    usage: "/night"
    permission: time.command
  gm0:
    description: §rTo Set your gamemode survial
    usage: "/gm0"
    permission: gamemode.command
  gm2:
    description: §rTo Set your gamemode to adventure
    usage: "/gm2"
    permission: gamemode.command
  gm1:
    description: §rTo Set your gamemode to creative
    usage: "/gm1"
    permission: gamemode.command
  gm3:
    description: §rTo Set your gamemode to spectator
    usage: "/gm3"
    permission: gamemode.command
  heal:
    description: §rTo Set your heath full.
    usage: "/heal"
    permission: heal.command
  food:
    description: §rTo Set your Hunger full.
    usage: "/food"
    permission: food.command


